interface FundDataType {
  code: string,	
  name: string,	
  type: string,	
  netWorth: string,	
  expectWorth: string,
  totalWorth: string,	
  expectGrowth: string,	
  dayGrowth: string,	
  lastWeekGrowth: string,	
  lastMonthGrowth: string,
  lastThreeMonthsGrowth: string,
  lastSixMonthsGrowth: string,	
  lastYearGrowth: string,	
  buyMin: Number,	
  buySourceRate: Number,	
  buyRate: Number,	
  manager: string,	
  fundScale: string,	
  worthDate: string,	
  expectWorthDate: string
}